name: xtr-eval
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - pytrec_eval
    - nltk
    - tensorflow==2.8.2
    - tensorflow_text==2.8.2
    - keras==2.8
    - transformers
    - scann==1.2.6
    - tensorflow-hub
    - beir
    - kagglehub
