name: xtr-eval
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - torch==2.4.1
    - pytrec_eval==0.5
    - nltk==3.9.1
    - tensorflow==2.17.0
    - tensorflow_text==2.17.0
    - keras==3.5.0
    - transformers==4.44.2
    - scann==1.3.4
    - tensorflow-hub==0.16.1
    - beir==2.0.0
    - kagglehub==0.3.0
    - huggingface_hub==0.25.0
    - matplotlib==3.9.2
    - jsonlines==4.0.0
    - jupyter==1.1.1
    - pyaml==24.7.0
# ---
# Install the required torch-scatter package:
#conda activate xtr-eval
#TORCH_VERSION=$(python -c "import torch; print(torch.__version__)")
#pip install torch-scatter -f "https://data.pyg.org/whl/torch-${TORCH_VERSION}.html"
#conda deactivate
# ---
